export const SCHEDULE_ADD_LECTURE = 'SCHEDULE_ADD_LECTURE'
export const SCHEDULE_REMOVE_LECTURE = 'SCHEDULE_REMOVE_LECTURE'

export const SCHEDULE_SAVE_ATTENDANCE_PREFERENCE = 'SCHEDULE_SAVE_ATTENDANCE_PREFERENCE'
export const SCHEDULE_CLEAR_LECTURES = 'SCHEDULE_CLEAR_LECTURES'

// My Schedule
export const SCHEDULE_CREATE_REQUEST = 'SCHEDULE_CREATE_REQUEST'
export const SCHEDULE_CREATE_SUCCESS = 'SCHEDULE_CREATE_SUCCESS'
export const SCHEDULE_CREATE_FAIL = 'SCHEDULE_CREATE_FAIL'
export const SCHEDULE_CREATE_RESET = 'SCHEDULE_CREATE_RESET'

export const SCHEDULE_DETAILS_REQUEST = 'SCHEDULE_DETAILS_REQUEST'
export const SCHEDULE_DETAILS_SUCCESS = 'SCHEDULE_DETAILS_SUCCESS'
export const SCHEDULE_DETAILS_FAIL = 'SCHEDULE_DETAILS_FAIL'

export const SCHEDULE_LIST_MY_REQUEST = 'SCHEDULE_LIST_MY_REQUEST'
export const SCHEDULE_LIST_MY_SUCCESS = 'SCHEDULE_LIST_MY_SUCCESS'
export const SCHEDULE_LIST_MY_FAIL = 'SCHEDULE_LIST_MY_FAIL'
export const SCHEDULE_LIST_MY_RESET = 'SCHEDULE_LIST_MY_RESET'